/**
 * Architect Agent
 * Designs system architecture, chooses tech stack, creates file structure
 */

import { callAIWithJSON } from '../llm/index.js';
import { saveToFile } from '../utils/fileWriter.js';
import type { TaskContract, AgentOutput } from './index.js';
import path from 'path';

export class ArchitectAgent {
  static async execute(contract: TaskContract): Promise<AgentOutput> {
    console.log('🏗️  Architect Agent: Designing system architecture...');

    const systemPrompt = `You are an expert software architect. Your job is to design a complete system architecture based on user requirements.

You must return a JSON object with this structure:
{
  "techStack": {
    "backend": "Node.js + Express + TypeScript",
    "frontend": "React + Next.js + TypeScript",
    "database": "PostgreSQL",
    "auth": "JWT + bcrypt"
  },
  "features": ["feature1", "feature2"],
  "apiEndpoints": [
    {"method": "POST", "path": "/api/auth/login", "description": "User login"},
    {"method": "GET", "path": "/api/products", "description": "List products"}
  ],
  "databaseSchema": {
    "users": {
      "id": "uuid primary key",
      "email": "varchar(255) unique",
      "password": "varchar(255)"
    },
    "products": {
      "id": "uuid primary key",
      "name": "varchar(255)",
      "price": "decimal(10,2)"
    }
  },
  "fileStructure": {
    "backend": ["src/server.ts", "src/routes/auth.ts"],
    "frontend": ["app/page.tsx", "components/Header.tsx"]
  },
  "recommendations": "Use microservices for scalability..."
}`;

    const userPrompt = `Objective: ${contract.objective}

User Requirements:
${JSON.stringify(contract.input, null, 2)}

Design a complete system architecture.`;

    const architecture = await callAIWithJSON([
      { role: 'system', content: systemPrompt },
      { role: 'user', content: userPrompt },
    ]);

    // Save architecture document
    const outputDir = path.join(
      process.env.OUTPUT_DIR!,
      `project-${contract.project_id}`
    );

    const archFile = await saveToFile(
      outputDir,
      'architecture/ARCHITECTURE.md',
      this.generateArchitectureDoc(architecture)
    );

    const techStackFile = await saveToFile(
      outputDir,
      'architecture/tech-stack.json',
      JSON.stringify(architecture.techStack, null, 2)
    );

    const apiSpecFile = await saveToFile(
      outputDir,
      'architecture/api-spec.json',
      JSON.stringify(architecture.apiEndpoints, null, 2)
    );

    const schemaFile = await saveToFile(
      outputDir,
      'architecture/database-schema.json',
      JSON.stringify(architecture.databaseSchema, null, 2)
    );

    return {
      success: true,
      filesGenerated: [archFile, techStackFile, apiSpecFile, schemaFile],
      outputPath: outputDir,
      summary: `Architecture designed: ${architecture.features.length} features, ${architecture.apiEndpoints.length} API endpoints`,
      metadata: architecture,
    };
  }

  private static generateArchitectureDoc(arch: any): string {
    return `# System Architecture

## Tech Stack
- **Backend:** ${arch.techStack.backend}
- **Frontend:** ${arch.techStack.frontend}
- **Database:** ${arch.techStack.database}
- **Authentication:** ${arch.techStack.auth}

## Features
${arch.features.map((f: string) => `- ${f}`).join('\n')}

## API Endpoints
${arch.apiEndpoints.map((e: any) => `- **${e.method}** \`${e.path}\` - ${e.description}`).join('\n')}

## Database Schema
${Object.entries(arch.databaseSchema).map(([table, fields]: [string, any]) => {
  return `### ${table}\n${Object.entries(fields).map(([col, type]) => `- ${col}: ${type}`).join('\n')}`;
}).join('\n\n')}

## Recommendations
${arch.recommendations}

---
*Generated by Devagent Architect Agent*
`;
  }
}
